from game.hilo import Hilo


class Director:
    """A person who directs the game. 
    
    The responsibility of a Director is to control the sequence of play.

    Attributes:

        self.card = 0   # keep the card worth generate for Hilo
        is_playing (boolean): Whether or not the game is being played.
        self.card1= 0 : Card generated by Hilo.
        self.card2= 0 : Predicted card by the user.
        self.wonPoints : if the prediction of the user ganme is correct.
        self.lostPoints :  if the prediction of the user ganme is correct.
        score (int): The score for one round of play. Starts with 300 points.

    """

    def __init__(self):
        """Constructs a new Director.
        
        Args:
            self (Director): an instance of Director.
        """
        self.card = 0   
        self.is_playing = True
        self.card1= 0
        self.card2= 0
        self.wonPoints = 100
        self.lostPoints = 75
        self.score = 300

    def start_game(self):
        """Starts the game by running the main game loop.
        
        Args:
            self (Director): an instance of Director.
        """
        self.card1 = self.do_updates()
        while self.is_playing:
            self.get_inputs()
            self.do_updates()
            # save the random card value for the next round.
            self.card1 =self.card2
            
    
    def get_inputs(self):
        """Ask the user if they want to roll.

        Args:
            self (Director): An instance of Director.
        """
  
        print(f"\n--- Your score is --- : {self.score} points\n")
        print(f"*** Your Initial Card is *** : {self.card1}\n")
        
        card_hand = input("The next card will be [h] high or [l] low? ")
        self.card2 = self.do_updates()
        print(f"\n+++ The next Card was +++ : {self.card2}\n")
        
        if card_hand == 'h' and self.card2 > self.card1 : 
            self.score += self.wonPoints 
            print(f"    Yes, it was higher, You won 100 points    \n")
        elif card_hand == 'l' and self.card2 < self.card1 :
            self.score += self.wonPoints
            print(f"    Yes, it was lower, You won 100 points    \n")
        #if the self.card1 = self.card2 , the score don't change
        elif self.card1 == self.card2:
            self.score = self.score
        else:    
            self.score -= self.lostPoints  
            print(f"    Ouch!, You lose 75 points!    \n")
        
        print(f"=== Your score is ==== : {self.score}\n")

        #The game ends when the score is inferior or equal to 0
        if self.score <= 0:
            print("=== Game over ====") # Great!
            self.is_playing = False
            return

        self.is_playing = (input('Do you want to play again? [y/n]:') == 'y')
        
        #if not, the game will end as well
        if not self.is_playing:
            print("=== Game over ====") # Great!
            return 
       
    def do_updates(self):

        """Updates the player's score.

        Args:
            self (Director): An instance of Director.
        """

        hilo = Hilo()
        hilo.cardhand()
        self.card = hilo.cardnumber
        
        return self.card


